plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bvalosek.cpuspy'
    compileSdk 34
    compileOptions.encoding = 'UTF-8'

    defaultConfig {
        applicationId "com.zoffcc.applications.cpuspy"
        minSdk 21
        targetSdk 34
        versionCode 20000
        versionName "2.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            // proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
        absolutePaths false
        // lintConfig file("lint.xml")
        showAll true
        textReport true
        xmlReport true
        htmlReport true
        textOutput file("lint-report.txt")
        htmlOutput file("lint-report.html")
        xmlOutput file("lint-report.xml")
    }

    compileOptions {
        encoding "UTF-8"
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // The app uses only standard Android SDK views and APIs; no external dependencies are required.
}
